# Generated by Django 5.1 on 2024-08-25 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_spams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spam',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
